name: saibr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.21.6
  - matplotlib=3.3.4
  - scipy=1.7.3
  - ipywidgets=7.5.1
  - scikit-learn=0.23.2
  - scikit-image==0.14.2
  - jupyter=1.0.0
  - pip
  - pip:
      - opencv-python==4.2.0.34
