name: saibr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - ipywidgets
  - jupyter
  - pip
  - pip:
      - saibr==0.1.1
      - opencv-python==4.2.0.34